flowchart TD
  n1["ผู้อำนวยการ"]
  n2["ผู้จัดการฝ่าย #40;ดูแลภาพรวม#41;"]
  n3["ทีมโครงการ"]
  n4["หัวหน้าโครงการ"]
  n5["นักวิเคราะห์"]
  n6["ผู้ทดสอบ"]
  n7["ผู้ประสานงาน"]
  n8["ผู้ดูแลระบบ"]
  n9["ผู้ดูแลรายงาน"]
  n1 --- n2
  n2 --- n3
  n3 --- n4
  n3 --- n5
  n3 --- n6
  n3 --- n7
  n2 --- n8
  n2 --- n9
